strongswan:
    image: connorpoole/strongswan:0.2.5
    environment:
        - RIGHT_HUB_ADDRESS=X.X.X.X
        - RIGHT_HUB_SUBNET=X.X.X.X/16
        - RIGHT_DEV_ADDRESS=X.X.X.X
        - RIGHT_DEV_SUBNET=X.X.X.X/16
        - RIGHT_ACCEPTANCE_ADDRESS=X.X.X.X
        - RIGHT_ACCEPTANCE_SUBNET=X.X.X.X/16
        - RIGHT_UNION_ADDRESS=X.X.X.X
        - RIGHT_UNION_SUBNET=X.X.X.X/16
        - RIGHT_REHEARSAL_ADDRESS=X.X.X.X
        - RIGHT_REHEARSAL_SUBNET=X.X.X.X/16
        - RIGHT_PROD_ADDRESS=X.X.X.X
        - RIGHT_PROD_SUBNET=X.X.X.X/16
        - LEFT_EDGE=1.1.1.1
        - LEFT_PRIVATE=172.16.10.100
        - LEFT_SUBNET=172.16.0.0/16
        - HUB_PSK=something
        - DEV_PSK=something
        - PROD_PSK=something
        - ACCEPTANCE_PSK=something
        - UNION_PSK=something
        - REHEARSAL_PSK=something
    net: host
    privileged: true
    cap_add:
        - ALL
    restart: always
